name: 'slack-notify'
description: This action does send slack-notify

inputs:
  status:
    required: false
    default: 'failure'
    description: when input status is not entered default failure
  slack_incoming_url:
    required: true
    description: slack incoming url

runs:
  using: 'composite'

  steps:
    - name: Send slack
      shell: bash
      run: |
        if [ "${{ inputs.status }}" = "success" ]; then
          EMOTICON="✅"
        else
          EMOTICON="⛔"
        fi

        MSG="{ \"username\": \"mergebot\",\"text\":\">${EMOTICON} workflow (<https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}|${GITHUB_WORKFLOW}>) in <https://github.com/${GITHUB_REPOSITORY}|${GITHUB_REPOSITORY}>\n><https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}/checks|${GITHUB_JOB}> job ${{ inputs.status }}, branch=\`${GITHUB_REF#refs/heads/}\`\", \"icon_emoji\": \":ghost:\"}"

        curl -X POST -H 'Content-type: application/json' --data "${MSG}" "${{ inputs.slack_incoming_url }}"
