name: Auto Merge on PR approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge PR on approval
        if: github.event.review.state == 'approved' && contains(github.event.pull_request.title, '[전체] - 자동 배포 PR')
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch origin ${{ github.event.pull_request.head.ref }}:refs/remotes/origin/${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.base.ref }}
          git merge --no-ff --no-edit ${{ github.event.pull_request.head.ref }}
          git push origin ${{ github.event.pull_request.base.ref }}

      - name: Send slack when failed
        if: ${{ failure() }}
        uses: ./.github/actions/slack-notify
        with:
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}

      - name: Send slack if completed
        if: ${{ success() }}
        uses: ./.github/actions/slack-notify
        with:
          status: success
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
